### ISSUE TITLE
Great project!

### ISSUE THREAD

**Issue by bruno222** [yossato/virtualgimbal_ros#1]
Great project, @yossato - You never thought of building an Action camera with 
- Raspberry
- [HQ camera](https://www.raspberrypi.org/products/raspberry-pi-high-quality-camera/)
- Gyro sensors
- And using your VirtualGimbal code for stabilization in the post-processing?

**Comment by yossato** [comment]
Thank you for your interesting idea. 

A high accuracy gyro sensor improves video stabilizing quality so do you know the gyro suitable for raspberry pi? The measurement frequency should more than 240 Hz. 

The post-processing makes footages more stable than a real time processing but the post-processing is tiresome work.
